# These are supported funding model platforms

github: nithin-murali-arch # Replace with your GitHub username
open_collective: # Replace with your Open Collective username if you have one
ko_fi: # Replace with your Ko-fi username if you have one
tidelift: # Replace with your Tidelift platform name if you have one
community_bridge: # Replace with your Community Bridge project name if you have one
liberapay: # Replace with your Liberapay username if you have one
issuehunt: # Replace with your IssueHunt username if you have one
otechie: # Replace with your Otechie username if you have one
custom: # Replace with your custom funding URL if you have one 